### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by oukunan**
Add Google Dictionary (by Google) in Chrome Extensions

### CODE REVIEW

**Comment by interaminense** [comment]
Hey @futurouz,
The extension link is missing. Could you add?

**Comment by oukunan** [comment]
@interaminense  Oh, sorry for my mistake. I'll add extension link.

**Comment by interaminense** [comment]
@futurouz,

**Comment by interaminense** [comment]
@futurouz,

Could you make a new Pull Request? This patch-1 branch is outdated. Its most updated branch is the "master"

**Pull request closed without merging**
